@baseAddress = http://localhost:5064

GET {{baseAddress}}/weatherforecast/
Accept: application/json

###

GET {{baseAddress}}/api/categories/
Accept: application/json

###
POST {{baseAddress}}/api/categories/
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1",
  "description": "Category 1 Description"
}
###
