@baseAddress = http://localhost:5064

@categoryId=08dd3a7a-e145-7854-c018-501ea6030000

GET {{baseAddress}}/api/categories/
Accept: application/json

###
POST {{baseAddress}}/api/categories/
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1",
  "description": "Category 1 Description"
}
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json

###
