@baseAddress = http://localhost:5064

@categoryIdC=08dd4773-edae-6335-c018-501ea6030000

@courseId=

GET {{baseAddress}}/api/categories/
Accept: application/json

###
POST {{baseAddress}}/api/categories/
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1",
  "description": "Category 1 Description"
}
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json

###


POST {{baseAddress}}/api/courses/
Accept: application/json
Content-Type: application/json
{
 "name": "New Course 5",
  "description": "This is a new course",
  "price": 99.99,
  "imageUrl": "http://example.com/picture.jpg",
  "categoryId": "{{categoryId}}"
}
###

GET {{baseAddress}}/api/courses
Accept: application/json
###




GET {{baseAddress}}/api/courses/{{categoryIdC}}
Accept: application/json
###

